site:
  title: Keycloak Benchmark
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://www.keycloak.org/keycloak-benchmark
  start_page: ROOT::index.adoc
content:
  sources:
    - url: https://github.com/keycloak/keycloak-benchmark
      start_paths:
        - doc/benchmark
        - doc/dataset
        - doc/kubernetes
        - doc/resilience
        - doc/ROOT
      branches:
        - 'main'

urls:
  latest_version_segment: latest
  html_extension_style: drop

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - '@antora/collector-extension'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental_ui
  output_dir: antora

runtime:
  fetch: true
  cache_dir: ./.cache/antora
  log:
    failure_level: warn

output:
  clean: true
  dir: _site/keycloak-benchmark

# Global asciidoc attributes here, used across all versions of documentation
asciidoc:
  extensions:
    - asciidoctor-kroki
    # Antora will resolve extensions listed here that end with something that looks like a file name extension as files relative to the project's folder
    # therefore append the slash
    - asciidoctor-highlight.js/
  attributes:
    kroki-fetch-diagram: true
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs-ext
    page-pagination: ''
    experimental: ''
    github-files: https://github.com/keycloak/keycloak-benchmark/blob/main
    project_name: Keycloak
    ispn: Infinispan
