# Workspace on the localhost
local_workspace: files/benchmark
local_kcb_home: "{{ local_workspace }}/keycloak-benchmark-{{ kcb_version }}"

# Workspace on the remote hosts
workspace: /opt
kcb_home: "{{ workspace }}/keycloak-benchmark-{{ kcb_version }}"

kcb_heap_size: 512m
kcb_clean_results: yes

update_system_packages: no
install_java: yes
java_version: 21

skip_install: no
