title: Kubernetes Guide
name: kubernetes-guide
version: '26.3.0'
nav:
  - modules/ROOT/nav.adoc
ext:
  collector:
    run:
      command: doc/kubernetes/collector/build.sh
    scan:
      dir: ./collector/target/kubernetes

