# Default values for keycloak-image-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: keycloak
customImage: false
useAWSJDBCWrapper: true
jdbcWrapperURL: https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/download/2.5.6/aws-advanced-jdbc-wrapper-2.5.6.jar
keycloakImage: quay.io/keycloak/keycloak:26.4.0
