# Setting use for ROSA default benchmark
cluster_size: 5
kcb_zip: ../benchmark/target/keycloak-benchmark-26.4.0-SNAPSHOT.zip
# GitHub actions seem to use different IP addresses for a single runner, which would then be rejected
cidr_ip: '0.0.0.0/0'
