# Create `env.yml` for the `aws_ec2.sh` and `benchmark.sh` scripts to pick up custom parameters.

# Overrides for AWS EC2. Defaults located in `roles/aws_ec2/defaults/main.yml`.
cluster_size: 2
instance_type: t3.small
instance_volume_size: 30

# Overrides for Keycloak Benchmark. Defaults located in `roles/benchmark/defaults/main.yml`.

# This will download this version from the GitHub releases
# kcb_version: 0.9-SNAPSHOT

# This will use a locally built version
kcb_zip: ../benchmark/target/keycloak-benchmark-0.11-SNAPSHOT.zip

kcb_heap_size: 1G
